### ISSUE TITLE
PX4-Autopilot Error solution

### ISSUE THREAD

**Issue by david-eskoundos** [dsor-isr/MIR-Competition-2024#1]
Hey guys,
when you try this command make px4_sitl gazebo-classic_glassy
![image](https://github.com/dsor-isr/MIR-Competition-2024/assets/86192151/f6d07dce-4cdb-40cf-bdae-dc391ae6ccdc)

You may got an error like that
AttributeError: module 'em' has no attribute 'RAW_OPT'

Just install an old version of empy: 
pip uninstall em
pip install empy==3.3.4

I hope that can help you

**Comment by joaolehodey** [comment]
Hello @DavidMicheal, thank you once again for your contribution. Again, I have added your solution to the troubleshooting section in the read-me (https://github.com/dsor-isr/MIR-Competition-2024/blob/main/README.md#troubleshooting).
