### ISSUE TITLE
install the uXRCE-DDS (PX4-ROS 2/DDS Bridge)

### ISSUE THREAD

**Issue by david-eskoundos** [dsor-isr/MIR-Competition-2024#2]
You can use this command:
sudo snap install micro-xrce-dds-agent --edge

to install it.
Because installing it locally gave me some errors.

but now you will start the agent with this command:
micro-xrce-dds-agent udp4 -p 8888

instead of this:
MicroXRCEAgent udp4 -p 8888

Thank youuuu <3

**Comment by joaolehodey** [comment]
Hello @DavidMicheal, thank you very much for your contribution, I have added your solution to a new troubleshooting section in the read-me (https://github.com/dsor-isr/MIR-Competition-2024/blob/main/README.md#troubleshooting).
